### ISSUE TITLE
投稿报错

### ISSUE THREAD

**Issue by zmq175** [Netrvin/telegram-submission-bot#1]
2018-12-04 02:34:38,103 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "main.py", line 251, in process_callback
    message_id=query.message.reply_to_message.message_id)
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python2.7/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
BadRequest: Chat not found

**Comment by zmq175** [comment]
审稿群可以接受到投稿 但是采用报错 超时

**Comment by zmq175** [comment]
bot并不能通过给bot发信息的方式实现广播

**Comment by axiref** [comment]
你可以换个机器人
